### PR TITLE
Fix Overall Overlay Plot issues: round 1

### LINKED ISSUE #12: User cannot add duplicate telemetry entries in an Overlay Plot for plotting multiple yKey components of the same telemetry entry
@nunoguedelha commented on [Tue Jul 06 2021](https://github.com/dic-iit/element_software-engineering/issues/61)

---

@nunoguedelha commented on [Tue Jul 06 2021](https://github.com/dic-iit/element_software-engineering/issues/61#issuecomment-874911259)

Related discussion in [Open MCT Discussions section](https://github.com/nasa/openmct/discussions): https://github.com/nasa/openmct/discussions/3883 .

---

## Issue Description

image

- It is not possible to display multiple fields/components of a telemetry domain object in an Overlay Plot without having to duplicate the actual domain object programmatically.
  image
- For the later to work, each new field added to the Overlay Plot requires a new duplicate of the original domain object. For each duplicate we select the desired field within the Overlay Plot settings and **not** within the added plot's child telemetry domain objets which are links to the original telemetry domain objets.

## How to Reproduce it

1. Create an "overlay" plot: select `Overlay Plot` from the drop-down `+CREATE` menu and land it in My Items.
   image
   image
1. drag and drop a telemetry domain object into the Overlay Plot, e.g. `IMU sensor measurements`.
   image
1. **If you try to drag the same object another time nothing happens, you still get a single object `IMU sensor measurements`.**
1. This problem can be worked around by duplicating the domain objects. Since it is not possible to duplicate a telemetry domain object from the contextual menus(not from the original nor the link under `My Items`),...
   | image | image |
   ...we create the duplicates programmatically, by editing directly the dictionary.[^1]
   image
   <details>
   <summary>`dictionaryIcubTelemetry.json`</summary>
   
   ```json
   {
     "name": "iCub Telemetry",
     "key": "icubtelemetry",
     "telemetryEntries": [
       {
         "name": "IMU sensor measurements",
         "key": "sens.imu.1",
         "type": "yarpopenmct.sensormeas",
         "values": [...]
       },
       {
         "name": "IMU sensor measurements (dupped)",
         "key": "sens.imu.2",
         "type": "yarpopenmct.sensormeas",
         "values": [...]
       },
       {
         "name": "IMU sensor measurements (dupped)",
         "key": "sens.imu.3",
         "type": "yarpopenmct.sensormeas",
         "values": [...]
       },
       ...
     ]
   }
   ```
   
   </details>
   <details>
   <summary>`icubtelemetry.js`</summary>
   
   ```js
   ICubTelemetry.prototype.parseFromId = function (id,sensorSample) {
       switch(id) {
           case "sens.imu.1":
           case "sens.imu.2":
           case "sens.imu.3":
               ...
       }
       ...
   }
   ```
   
   </details>

   <details>
   <summary>`icubtelemetry.js`</summary>
   
   ```json
   {
     ...
     "portInConfig": {
         "sens.imu.1": {
             "yarpName": "${this.robotYarpPortPrefix}/inertial",
             "localName": "${this.localYarpPortPrefix}/inertial.1:i",
             "portType": "bottle",
             "parser": {
                 "type": "internal",
                 "outputFormat": "fromId"
             }
         },
         "sens.imu.2": {
             "yarpName": "${this.robotYarpPortPrefix}/inertial",
             "localName": "${this.localYarpPortPrefix}/inertial.2:i",
             "portType": "bottle",
             "parser": {
                 "type": "internal",
                 "outputFormat": "fromId"
             }
         },
         "sens.imu.3": {
             "yarpName": "${this.robotYarpPortPrefix}/inertial",
             "localName": "${this.localYarpPortPrefix}/inertial.3:i",
             "portType": "bottle",
             "parser": {
                 "type": "internal",
                 "outputFormat": "fromId"
             }
         },
     }
   }
   ```

   </details>
   Needless to say that this approach is quite cumbersome as soon as you get many components in a telemetry domain object, and in any case is not user friendly.

[^1]: Setting the Domain Object Type `yarpopenmct.sensormeas` property `creatable` to `true` adds the type to the `+CREATE` menu and allows users to create it and lnd it in `My Items` for instance. But as we can see in the description depicted below, this is just a type and doesn't include metadata information of the `IMU sensor measurements`. It's just much easier to duplicate the folded entry in the dictionary.
      <details>
      <summary>"iCub Sensor Telemetry Entry" type exported description</summary>

      image
      
      ```json
      {
        "openmct": {
          "d4f0691e-ecb7-4750-add0-7b53a2f46103": {
            "name": "iCub Sensor Telemetry Entry",
            "type": "yarpopenmct.sensormeas",
            "location": "mine",
            "modified": 1654195860726,
            "persisted": 1654195808718,
            "id": "d4f0691e-ecb7-4750-add0-7b53a2f46103",
            "identifier": {
              "namespace": "",
              "key": "d4f0691e-ecb7-4750-add0-7b53a2f46103"
            }
          }
        },
        "rootId": "d4f0691e-ecb7-4750-add0-7b53a2f46103"
      }
      ```
      
      </details>

## Desired Behaviour

We would like to be able to display multiple components of a Telemetry Domain Object that has been dragged in an Overlay Plot by selecting those components directly in the Overlay Plot settings without the need to duplicate the Domain Object.

### PR DESCRIPTION
**Pull request by nunoguedelha**
Closes #12 , #14 , #15 .

### Describe your changes:

This is a bundle fix for the issues listed above, which are part of the epic #11 .

image

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [ ] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by nunoguedelha** [comment]
CC @S-Dafarra. Stefano, the multi-component plot is now working fine, also with further fixes on the plot top legend table.

**Comment by nunoguedelha** [comment]
This time, as this fix was urgent, I waved the explanations in the issues. I'll do it later when I have more bandwidth.

**Review by traversaro — APPROVED** [review]

**Comment by nunoguedelha** [comment]
For some reason the PR is displaying commits already merged in the `1.7.8-iit` branch. Trying to fix that...

**Comment by nunoguedelha** [comment]
Thanks @traversaro .

**Pull request merged**
